const productboxes = [
  {
    id: 1,
    name: "modern furniture",
    img: "../image/bed1.jpg",
    quantity: "1",
    multiply: "x",
    price: "$140.00",
  },
  {
    id: 2,
    name: "modern furniture",
    img: "image/Dining Room/diningchair1.jpg",
    quantity: "1",
    multiply: "x",
    price: "$140.00",
  },
  {
    id: 3,
    name: "modern furniture",
    img: "image/cart-img-3.jpg",
    quantity: "1",
    multiply: "x",
    price: "$140.00",
  },
  {
    id: 4,
    name: "modern furniture",
    img: "image/cart-img-4.jpg",
    quantity: "1",
    multiply: "x",
    price: "$140.00",
  },
  {
    id: 5,
    name: "modern furniture",
    img: "image/cart-img-5.jpg",
    quantity: "1",
    multiply: "x",
    price: "$140.00",
  },
  {
    id: 6,
    name: "modern furniture",
    img: "image/cart-img-6.jpg",
    quantity: "1",
    multiply: "x",
    price: "$140.00",
  },
  {
    id: 7,
    name: "modern furniture",
    img: "image/cart-img-6.jpg",
    quantity: "1",
    multiply: "x",
    price: "$140.00",
  },
  {
    id: 8,
    name: "modern furniture",
    img: "image/cart-img-6.jpg",
    quantity: "1",
    multiply: "x",
    price: "$140.00",
  },
  {
    id: 9,
    name: "modern furniture",
    img: "image/cart-img-6.jpg",
    quantity: "1",
    multiply: "x",
    price: "$140.00",
  },
  {
    id: 10,
    name: "modern furniture",
    img: "image/cart-img-6.jpg",
    quantity: "1",
    multiply: "x",
    price: "$140.00",
  },
  {
    id: 11,
    name: "modern furniture",
    img: "image/cart-img-6.jpg",
    quantity: "1",
    multiply: "x",
    price: "$140.00",
  },
  {
    id: 12,
    name: "modern furniture",
    img: "image/cart-img-6.jpg",
    quantity: "1",
    multiply: "x",
    price: "$140.00",
  },
  {
    id: 13,
    name: "modern furniture",
    img: "image/cart-img-6.jpg",
    quantity: "1",
    multiply: "x",
    price: "$140.00",
  },
];

export default productboxes;
